### ISSUE TITLE
How to get the VASA-drop cell-specific barcode file 

### ISSUE THREAD

**Issue by kiritosuki1** [anna-alemany/VASAseq#1]
Hi
I wonder that how can i get the VASA-drop barcode from the fastq file . I recently repeat your article result,but  i do not find how you get the VASA-drop barcode. Could you provide me with a wrokflow. 

Thanks 
Jiaze

**Comment by anna-alemany** [comment]
Dear Jiaze, 

I use this line of bash code: 
```
zcat $file | awk -v x0=$start_position -v L=$length '{if (FNR%4==2) {w=substr($0,x0,L); count[w]++}} END {for (bc in count) print bc, count[bc]}' | sort -k2nr | awk '{OFS="\t"} {print $1,$2}' > ${file%.f*q.gz}_barcodes.tsv
```
where `file` is the zipped R1 fastq file; start_position is the initial position of the barcode, and length is the length of the barcode, to count how many times each barcode is detected. Then, I make a scatter plot showing ranked-barcodes (x-axis) versus frequency (y-axis) and determine the position of the elbow. 

Best,
Anna
