### ISSUE TITLE
There may be something wrong in concatenator.py

### ISSUE THREAD

**Issue by william0701** [anna-alemany/VASAseq#2]
Hi,

Thanks for your great work. But I find there may be something wrong in the concatenator.py file. I think the concatenator.py is used to seperate the reads based on the cell barcodes. To do this, you use the the `allbc_df` to store the original barcodes and the accepted mismatch barcodes, and the `fout` is a dictionary with the original barcodes as keys and the corresponding output interface as values. However, in the step of writting files in line 147-150, you use the `cellbcseq` as the key to find the corresponding output like this:
`if not demux:        
    fout.write( '\n'.join([name, s, '+', q, '']))       
else:        
   fout[cellbcseq].write('\n'.join([name, s, '+', q, '']))`  
The `cellbcseq` is the barcode of current read, which may be mismatched. Therefore, I think current codes can only get the reads with exactly correct barcodes, no matter what the paramter `hd` is. I guess the `cellbcseq` should be replaced by `originalBC`, which will support the mismatch of barcodes.

Thanks for you time, please let me know if I was wrong!

**Comment by anna-alemany** [comment]
Dear William0701, 

Thanks for pointing out at this bug. Indeed, you are right: in this line of code, `cellbcseq` should be replaced by `originalBC`. This is particularly important if demux is set to True (which I am relieved to say was not in the published analysed data!).

Thanks again!

**Comment by gouthamatla** [comment]
May I ask if this is fixed in the code ?
